name: Captura Inicial do FTP

on:
  workflow_dispatch:

jobs:
  get-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repo
        uses: actions/checkout@v3

      - name: Baixar arquivos da Nuvemshop
        uses: airbnb/ftp-sync-action@v1.0.3
        with:
          host: ftp.nuvemshop.com.br
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          options: "--verbose"

      - name: Commitar arquivos no GitHub
        run: |
          git config --global user.name "Richard Almeida"
          git config --global user.email "richard.almeida@exemplo.com"
          git add .
          git commit -m "Captura inicial de arquivos via FTP" || echo "Sem mudanças"
          git push
